# File: alembic/versions/df75d986ebf5_create_ndvi_analyses_table.py
"""create ndvi_analyses table

Revision ID: df75d986ebf5
Revises: 
Create Date: 2024-11-24 19:50:40.566162
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'df75d986ebf5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ndvi_analyses',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('bbox', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('geometry', Geometry('POLYGON', srid=4326), nullable=True),
        sa.Column('ndvi_stats', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('red_url', sa.String(), nullable=True),
        sa.Column('nir_url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_ndvi_analyses_geometry ON ndvi_analyses USING gist (geometry)')
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ndvi_analyses_geometry', table_name='ndvi_analyses', postgresql_using='gist')
    op.drop_table('ndvi_analyses')
    # ### end Alembic commands ###